### PR TITLE
Adding Fold to Function Body

### PR DESCRIPTION
**Pull request by ngmachado**
I find useful to have a folding option in the syntax definition.

If you find also useful, we can start tunning the folding to other parts.

_p.s - I made the same pull request to tomlion rep by mistake._ 

Cheers

### CODE REVIEW

**Comment by TovarishFin** [comment]
I personally do not find it to be useful. But I have only been using vim for about 2 - 3 months. I am sure others would find it to be useful. I haven't really gotten into folding in relating to syntax files. But feel free to add in more changes for this if you want.

**Comment by TovarishFin** [comment]
If you are adding folding for function bodies, should you perhaps add in the same for contracts, conditionals, loops etc? I can wait for changes or just merge this in. All the same to me.

**Comment by TovarishFin** [comment]
@ngmachado I never got an answer from you. Did you want me to merge this in or should I wait for more updates from you for the folding functionality?

**Comment by ngmachado** [comment]
Sorry, don't merge this PR. I will submit a more complete solution to folding.

**Comment by TovarishFin** [comment]
ok great!

**Comment by TovarishFin** [comment]
@ngmachado it has been quite some time since I heard anything about this PR. I am going to close it since last I heard from you it was not complete.

**Pull request closed without merging**
